"""cambie nombre de tabla

Revision ID: 920235e63caa
Revises: 98bdf34b0b01
Create Date: 2023-05-28 19:11:42.199348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920235e63caa'
down_revision = '98bdf34b0b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('area_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='area_model_pkey')
    )
    op.drop_table('areas')
    # ### end Alembic commands ###
